### ISSUE TITLE
Code for the generated graphics.

### ISSUE THREAD

**Issue by thewickedkarma** [ohjay/turtledraw#2]
Where to get the code for generated graphics?

**Comment by thewickedkarma** [comment]
Help, it's not working

```
Traceback (most recent call last):
  File "svgparse.py", line 506, in <module>
    handle_path(path)
  File "svgparse.py", line 486, in handle_path
    Mx, My, clz = int(d[0][1:]), int(d[1]), d[2:]
ValueError: invalid literal for int() with base 10: ''

```
